#!/bin/bash

#   delete-vm - Delete a virtual machine created with create-vm

VM=$1

# Set VM_IMAGE_DIR environment variable to override default storage location for VMs
VM_IMAGE_DIR=${VM_IMAGE_DIR:-"/data/libvirt"}

VM_IMAGE="${VM_IMAGE_DIR}/images/$VM.qcow2"
CI_IMAGE="${VM_IMAGE_DIR}/images/$VM-cidata.img"

usage()
{
cat << EOF
usage: $0 vmname
EOF
}

if [[ -z $VM ]]; then
    usage
    exit 1
fi

if [[ -e $VM_IMAGE ]]; then
    # VM exists
    virsh destroy "$VM"
    virsh undefine "$VM"
    rm -fv "$VM_IMAGE" "$CI_IMAGE"
    rm -fv ${VM_IMAGE_DIR}/xml/${VM}.xml
else
    echo "Cannot find an VM image file named '$VM_IMAGE'. Attempting undefine..."
    virsh undefine "$VM"
fi
