#!/bin/bash

#   get-node-ip - Get the IP address of a VM managed by virsh.

usage()
{
cat << EOF
usage: $0 hostname

This script will take a virsh-managed VM hostname and return the IP address.
EOF
}

HOSTNAME=$1

if [[ -z $HOSTNAME ]]; then
    echo "ERROR: Hostname is required"
    usage
    exit 1
fi

MAC=$(virsh -q domiflist $HOSTNAME | awk '{ print $5 }')
arp -e | grep -i $MAC | awk '{ print $1 }'
